### ISSUE TITLE
Make z-index actually optional

### ISSUE THREAD

**Issue by tmcw** [tmcw/memory-geojson#3]
Not clear how yet. Could be a magic number?

I think, actually, the best way is -0. It's impossible to represent in JSON.

**Comment by tmcw** [comment]
Done in #4

**Comment by rowanwins** [comment]
The [ArcGIS PBF handles this](https://github.com/Esri/arcgis-pbf/blob/main/proto/FeatureCollection/FeatureCollection.proto#L178) by having a per feature flag called `hasZ`.
If that's true then you grab 3 values from the coordinates array, if it's false then you only take 2 values.
The ArcGIS approach means you don't need to store unnecessary data or correctly interpret magic numbers, so that might be an alternate approach.

**Comment by tmcw** [comment]
That approach would save some data, but it seems like it'd create a subtle incompatibility with GeoJSON - Geometries in the spec can have a mix of 2 and 3-coordinate positions, there's no requirement for, for example, a MultiPoint to have all points with altitude or all points without altitude, it can be a mix.
